In [1]:
import pandas as pd
import numpy as np

In [2]:
A = ['Cs', 'MA', 'FA', 'Rb']
B1 = ['Na', 'K', 'Ag']
B3 = ['Bi', 'In', 'Sb', 'Sc', 'La', 'Y']
X = ['Cl', 'Br', 'I']

In [3]:
size = len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*len(X)
size

209952

In [4]:
columns = ['Material', 'Cs', 'MA', 'FA', 'Rb', 'Pb', 'Cd', 'Bi', 'Sn',
       'Na', 'In', 'Sb', 'K', 'Cu', 'Ag', 'Mn', 'Eu', 'Zn', 'Sc', 'La', 'Y', 'Cl', 'Br',
       'I', 'Dimensionality']

In [5]:
data=np.zeros(shape=[size,len(columns)])

In [6]:
Data = pd.DataFrame(data=data,columns=columns)
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209952 entries, 0 to 209951
Data columns (total 25 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Material        209952 non-null  float64
 1   Cs              209952 non-null  float64
 2   MA              209952 non-null  float64
 3   FA              209952 non-null  float64
 4   Rb              209952 non-null  float64
 5   Pb              209952 non-null  float64
 6   Cd              209952 non-null  float64
 7   Bi              209952 non-null  float64
 8   Sn              209952 non-null  float64
 9   Na              209952 non-null  float64
 10  In              209952 non-null  float64
 11  Sb              209952 non-null  float64
 12  K               209952 non-null  float64
 13  Cu              209952 non-null  float64
 14  Ag              209952 non-null  float64
 15  Mn              209952 non-null  float64
 16  Eu              209952 non-null  float64
 17  Zn              209952 non-null  float64
 18  Sc              209952 non-null  float64
 19  La              209952 non-null  float64
 20  Y               209952 non-null  float64
 21  Cl              209952 non-null  float64
 22  Br              209952 non-null  float64
 23  I               209952 non-null  float64
 24  Dimensionality  209952 non-null  float64
dtypes: float64(25)
memory usage: 40.0 MB

In [7]:
for i in range(len(A)):
    for j in range(len(A)):
        for k in range(len(B1)):
            for l in range (len(B3)):
                for m in range (len(X)):
                    for n in range (len(X)):
                        for o in range (len(X)):
                            for p in range (len(X)):
                                for q in range (len(X)):
                                    for r in range (len(X)):
                                        if A[i] == 'Cs' : Data["Cs"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[i] == 'MA' : Data["MA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[i] == 'FA' : Data["FA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[i] == 'Rb' : Data["Rb"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'Cs' : Data["Cs"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'MA' : Data["MA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'FA' : Data["FA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'Rb' : Data["Rb"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B1[k] == 'Na' : Data["Na"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B1[k] == 'K' : Data["K"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B1[k] == 'Ag' : Data["Ag"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B3[l] == 'Bi' : Data["Bi"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B3[l] == 'In' : Data["In"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B3[l] == 'Sb' : Data["Sb"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B3[l] == 'Sc' : Data["Sc"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B3[l] == 'La' : Data["La"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B3[l] == 'Y' : Data["Y"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[m] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[m] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[m] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[n] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[n] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[n] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[o] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[o] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[o] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[p] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[p] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[p] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[q] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[q] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[q] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[r] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[r] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[r] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B1)*l)+(len(A)*len(A)*len(B1)*len(B3)*m)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*n)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*o)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B1)*len(B3)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
            #if j==k: Data.drop(index =[i+(len(A)*j)+(len(A)*len(B)*k)+(len(A)*len(B)*len(B)*l)],inplace = False)
Data

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209947,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
209948,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
209949,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
209950,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
209951,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0

In [10]:
Data.shape

(209952, 25)

In [13]:
Data.shape[0]

209952

In [18]:
Data.Material=""
Data2 = Data.drop_duplicates()
Data3 = Data2.reset_index(drop=True)
Data3

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
1,,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
2,,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
3,,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
4,,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5036,,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5037,,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5038,,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5039,,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0

In [19]:
Data3["Material"]=""
for i in range(Data3.shape[0]):
    for var in Data3.iloc[:,1:]:
        if Data3[var][i]!=0:
            Data3["Material"][i]= str(Data3["Material"][i])+str(var)+str(int(Data3[var][i]))
Data3

/var/folders/hy/sb8f_z2j1hxg_09pbh5s7myr0000gn/T/ipykernel_51423/3935339571.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data3["Material"][i]= str(Data3["Material"][i])+str(var)+str(int(Data3[var][i]))

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,Cs2Bi1Na1Cl6,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
1,Cs1MA1Bi1Na1Cl6,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
2,Cs1FA1Bi1Na1Cl6,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
3,Cs1Rb1Bi1Na1Cl6,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
4,MA2Bi1Na1Cl6,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,MA1FA1Ag1Y1I6,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5036,MA1Rb1Ag1Y1I6,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5037,FA2Ag1Y1I6,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5038,FA1Rb1Ag1Y1I6,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0
5039,Rb2Ag1Y1I6,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0

In [20]:
ra =(Data3['Cs']*188+Data3['MA']*270+Data3['FA']*279+Data3['Rb']*172)/2
ra

0       188.0
1       229.0
2       233.5
3       180.0
4       270.0
        ...
5035    274.5
5036    221.0
5037    279.0
5038    225.5
5039    172.0
Length: 5040, dtype: float64

In [21]:
RA = pd.DataFrame(data=ra,columns={'RA'})
RA

         RA
0     188.0
1     229.0
2     233.5
3     180.0
4     270.0
...     ...
5035  274.5
5036  221.0
5037  279.0
5038  225.5
5039  172.0

[5040 rows x 1 columns]

In [22]:
rb=(Data3['Pb']*119+Data3['Cd']*95+Data3['Bi']*103+Data3['Sn']*118+Data3['Na']*102+Data3['In']*80+Data3['Sb']*76+Data3['K']*138+Data3['Cu']*77+Data3['Ag']*115+Data3['Mn']*83+Data3['Eu']*117+Data3['Zn']*74+Data3['Sc']*75.5+Data3['La']*103.2+Data3['Y']*90)/2
rb

0       102.5
1       102.5
2       102.5
3       102.5
4       102.5
        ...
5035    102.5
5036    102.5
5037    102.5
5038    102.5
5039    102.5
Length: 5040, dtype: float64

In [23]:
RB = pd.DataFrame(data=rb,columns={'RB'})
RB

         RB
0     102.5
1     102.5
2     102.5
3     102.5
4     102.5
...     ...
5035  102.5
5036  102.5
5037  102.5
5038  102.5
5039  102.5

[5040 rows x 1 columns]

In [24]:
rx = (Data3['Cl']*181+Data3['Br']*196+Data3['I']*220)/6
rx

0       181.0
1       181.0
2       181.0
3       181.0
4       181.0
        ...
5035    220.0
5036    220.0
5037    220.0
5038    220.0
5039    220.0
Length: 5040, dtype: float64

In [25]:
RX = pd.DataFrame(data=rx,columns={'RX'})
RX

         RX
0     181.0
1     181.0
2     181.0
3     181.0
4     181.0
...     ...
5035  220.0
5036  220.0
5037  220.0
5038  220.0
5039  220.0

[5040 rows x 1 columns]

In [26]:
gtf = (ra+rx)/(1.414*(rb+rx))
gtf

0       0.920500
1       1.022778
2       1.034004
3       0.900544
4       1.125056
          ...
5035    1.084394
5036    0.967073
5037    1.094262
5038    0.976942
5039    0.859621
Length: 5040, dtype: float64

In [27]:
GTF = pd.DataFrame(data=gtf,columns={"Goldschmidt's"})
GTF

      Goldschmidt's
0          0.920500
1          1.022778
2          1.034004
3          0.900544
4          1.125056
...             ...
5035       1.084394
5036       0.967073
5037       1.094262
5038       0.976942
5039       0.859621

[5040 rows x 1 columns]

In [28]:
rxb=rx/rb
rab=ra/rb
lrab= np.log(rab)

In [29]:
bartel =(rxb) - 1*(1-(rab/lrab))
bartel

0       3.789608
1       3.545129
2       3.532762
3       3.884511
4       3.485508
          ...
5035    3.864929
5036    3.952664
5037    3.864626
5038    3.936600
5039    4.388123
Length: 5040, dtype: float64

In [30]:
Bartel = pd.DataFrame(data=bartel,columns={'Bartel et al'})
Bartel

      Bartel et al
0         3.789608
1         3.545129
2         3.532762
3         3.884511
4         3.485508
...            ...
5035      3.864929
5036      3.952664
5037      3.864626
5038      3.936600
5039      4.388123

[5040 rows x 1 columns]

In [1]:
sdt= np.ones(5040)

NameError: name 'np' is not defined

In [31]:
DataF=pd.concat([Data3,RA,RB,RX,GTF,Bartel],axis=1)
DataF

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Y,Cl,Br,I,Dimensionality,RA,RB,RX,Goldschmidt's,Bartel et al
0,Cs2Bi1Na1Cl6,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,188.0,102.5,181.0,0.920500,3.789608
1,Cs1MA1Bi1Na1Cl6,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,229.0,102.5,181.0,1.022778,3.545129
2,Cs1FA1Bi1Na1Cl6,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,233.5,102.5,181.0,1.034004,3.532762
3,Cs1Rb1Bi1Na1Cl6,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,180.0,102.5,181.0,0.900544,3.884511
4,MA2Bi1Na1Cl6,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,270.0,102.5,181.0,1.125056,3.485508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,MA1FA1Ag1Y1I6,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,274.5,102.5,220.0,1.084394,3.864929
5036,MA1Rb1Ag1Y1I6,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,221.0,102.5,220.0,0.967073,3.952664
5037,FA2Ag1Y1I6,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,279.0,102.5,220.0,1.094262,3.864626
5038,FA1Rb1Ag1Y1I6,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,225.5,102.5,220.0,0.976942,3.936600
5039,Rb2Ag1Y1I6,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,172.0,102.5,220.0,0.859621,4.388123

In [33]:
DataF.Material=DataF.Material.str.replace("1","")
DataF

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Y,Cl,Br,I,Dimensionality,RA,RB,RX,Goldschmidt's,Bartel et al
0,Cs2BiNaCl6,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,188.0,102.5,181.0,0.920500,3.789608
1,CsMABiNaCl6,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,229.0,102.5,181.0,1.022778,3.545129
2,CsFABiNaCl6,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,233.5,102.5,181.0,1.034004,3.532762
3,CsRbBiNaCl6,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,180.0,102.5,181.0,0.900544,3.884511
4,MA2BiNaCl6,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,6.0,0.0,0.0,0.0,270.0,102.5,181.0,1.125056,3.485508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5035,MAFAAgYI6,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,274.5,102.5,220.0,1.084394,3.864929
5036,MARbAgYI6,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,221.0,102.5,220.0,0.967073,3.952664
5037,FA2AgYI6,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,279.0,102.5,220.0,1.094262,3.864626
5038,FARbAgYI6,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,225.5,102.5,220.0,0.976942,3.936600
5039,Rb2AgYI6,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,6.0,0.0,172.0,102.5,220.0,0.859621,4.388123

In [ ]:
DataF2=

In [34]:
DataF.to_excel('A2BBX6_1_3.xlsx')

# Intermediate