In [1]:
import pandas as pd
import numpy as np

In [2]:
A = ['Cs', 'MA', 'FA', 'Rb']
B = ['Pb', 'Cd', 'Sn', 'Mn', 'Eu', 'Zn']
X = ['Cl', 'Br', 'I']

In [3]:
size = len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*len(X)
size

69984

In [4]:
columns = ['Material', 'Cs', 'MA', 'FA', 'Rb', 'Pb', 'Cd', 'Bi', 'Sn',
       'Na', 'In', 'Sb', 'K', 'Cu', 'Ag', 'Mn', 'Eu', 'Zn', 'Sc', 'La', 'Y', 'Cl', 'Br',
       'I', 'Dimensionality']

In [54]:
data=np.zeros(shape=[size,len(columns)])

In [55]:
Data = pd.DataFrame(data=data,columns=columns)
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69984 entries, 0 to 69983
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Material        69984 non-null  float64
 1   Cs              69984 non-null  float64
 2   MA              69984 non-null  float64
 3   FA              69984 non-null  float64
 4   Rb              69984 non-null  float64
 5   Pb              69984 non-null  float64
 6   Cd              69984 non-null  float64
 7   Bi              69984 non-null  float64
 8   Sn              69984 non-null  float64
 9   Na              69984 non-null  float64
 10  In              69984 non-null  float64
 11  Sb              69984 non-null  float64
 12  K               69984 non-null  float64
 13  Cu              69984 non-null  float64
 14  Ag              69984 non-null  float64
 15  Mn              69984 non-null  float64
 16  Eu              69984 non-null  float64
 17  Zn              69984 non-null  float64
 18  Sc              69984 non-null  float64
 19  La              69984 non-null  float64
 20  Y               69984 non-null  float64
 21  Cl              69984 non-null  float64
 22  Br              69984 non-null  float64
 23  I               69984 non-null  float64
 24  Dimensionality  69984 non-null  float64
dtypes: float64(25)
memory usage: 13.3 MB

In [56]:
for i in range(len(A)):
    for j in range(len(A)):
        for k in range(len(B)):
            for l in range (len(X)):
                    for n in range (len(X)):
                        for o in range (len(X)):
                            for p in range (len(X)):
                                for q in range (len(X)):
                                    for r in range (len(X)):
                                        if A[i] == 'Cs' : Data["Cs"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[i] == 'MA' : Data["MA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[i] == 'FA' : Data["FA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[i] == 'Rb' : Data["Rb"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'Cs' : Data["Cs"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'MA' : Data["MA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'FA' : Data["FA"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if A[j] == 'Rb' : Data["Rb"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if B[k] == 'Pb' : Data["Pb"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 2
                                        if B[k] == 'Cd' : Data["Cd"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 2
                                        if B[k] == 'Sn' : Data["Sn"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 2
                                        if B[k] == 'Mn' : Data["Mn"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 2
                                        if B[k] == 'Eu' : Data["Eu"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 2
                                        if B[k] == 'Zn' : Data["Zn"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 2
                                        if X[l] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[l] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[l] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[n] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[n] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[n] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[o] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[o] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[o] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[p] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[p] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[p] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[q] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[q] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[q] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[r] == 'Cl' : Data["Cl"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[r] == 'Br' : Data["Br"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
                                        if X[r] == 'I' : Data["I"][i+(len(A)*j)+(len(A)*len(A)*k)+(len(A)*len(A)*len(B)*l)+(len(A)*len(A)*len(B)*len(X)*n)+(len(A)*len(A)*len(B)*len(X)*len(X)*o)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*p)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*q)+(len(A)*len(A)*len(B)*len(X)*len(X)*len(X)*len(X)*len(X)*r)] += 1
            #if j==k: Data.drop(index =[i+(len(A)*j)+(len(A)*len(B)*k)+(len(A)*len(B)*len(B)*l)],inplace = False)
 #               if j==k :
 #                   Data.iloc[i+(len(A)*j)+(len(A)*len(B)*k)+(len(A)*len(B)*len(B)*l),0] =str(A[i]+'2'+B[j]+'2'+X[l]+'6')
 #               if j!=k :
 #                   Data.iloc[i+(len(A)*j)+(len(A)*len(B)*k)+(len(A)*len(B)*len(B)*l),0] =str(A[i]+'2'+B[j]+B[k]+X[l]+'6')

In [57]:
Data

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
2,0.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
4,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69979,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
69980,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
69981,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
69982,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
69983,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0

In [58]:
Data.describe()

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
count,69984.0,69984.000000,69984.000000,69984.000000,69984.000000,69984.000000,69984.000000,69984.0,69984.000000,69984.0,...,69984.000000,69984.000000,69984.000000,69984.0,69984.0,69984.0,69984.000000,69984.000000,69984.000000,69984.0
mean,0.0,0.500000,0.500000,0.500000,0.500000,0.333333,0.333333,0.0,0.333333,0.0,...,0.333333,0.333333,0.333333,0.0,0.0,0.0,2.000000,2.000000,2.000000,0.0
std,0.0,0.612377,0.612377,0.612377,0.612377,0.745361,0.745361,0.0,0.745361,0.0,...,0.745361,0.745361,0.745361,0.0,0.0,0.0,1.154709,1.154709,1.154709,0.0
min,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0
25%,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,1.000000,1.000000,1.000000,0.0
50%,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,2.000000,2.000000,2.000000,0.0
75%,0.0,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,3.000000,3.000000,3.000000,0.0
max,0.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.0,2.000000,0.0,...,2.000000,2.000000,2.000000,0.0,0.0,0.0,6.000000,6.000000,6.000000,0.0

In [59]:
Data.iloc[:,1:]=Data.iloc[:,1:]/2

In [60]:
Data

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
1,0.0,0.5,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
2,0.0,0.5,0.0,0.5,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
3,0.0,0.5,0.0,0.0,0.5,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
4,0.0,0.5,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69979,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69980,0.0,0.5,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69981,0.0,0.0,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69982,0.0,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69983,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0

In [61]:
Data.Material=""

In [62]:
Data2 = Data.drop_duplicates()

In [63]:
Data2

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
1,,0.5,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
2,,0.5,0.0,0.5,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
3,,0.5,0.0,0.0,0.5,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
5,,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69974,,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69975,,0.0,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69978,,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69979,,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
69983,,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0

In [64]:
Data3 = Data2.reset_index(drop= True)
Data3

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
1,,0.5,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
2,,0.5,0.0,0.5,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
3,,0.5,0.0,0.0,0.5,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
4,,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1676,,0.0,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1677,,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1678,,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1679,,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0

In [82]:
Data3["Material"]=""
for i in range(Data3.shape[0]):
    for var in Data3.iloc[:,1:]:
        if Data3[var][i]!=0:
            Data3["Material"][i]= str(Data3["Material"][i])+str(var)+str(float(Data3[var][i]))
Data3

/var/folders/hy/sb8f_z2j1hxg_09pbh5s7myr0000gn/T/ipykernel_38971/3858558235.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data3["Material"][i]= str(Data3["Material"][i])+str(var)+str(float(Data3[var][i]))

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Mn,Eu,Zn,Sc,La,Y,Cl,Br,I,Dimensionality
0,Cs1.0Pb1.0Cl3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
1,Cs0.5MA0.5Pb1.0Cl3.0,0.5,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
2,Cs0.5FA0.5Pb1.0Cl3.0,0.5,0.0,0.5,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
3,Cs0.5Rb0.5Pb1.0Cl3.0,0.5,0.0,0.0,0.5,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
4,MA1.0Pb1.0Cl3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,MA0.5FA0.5Zn1.0I3.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1676,MA0.5Rb0.5Zn1.0I3.0,0.0,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1677,FA1.0Zn1.0I3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1678,FA0.5Rb0.5Zn1.0I3.0,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0
1679,Rb1.0Zn1.0I3.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0

In [66]:
ra =(Data3['Cs']*188+Data3['MA']*270+Data3['FA']*279+Data3['Rb']*172)
ra

0       188.0
1       229.0
2       233.5
3       180.0
4       270.0
        ...
1675    274.5
1676    221.0
1677    279.0
1678    225.5
1679    172.0
Length: 1680, dtype: float64

In [67]:
RA = pd.DataFrame(data=ra,columns={'RA'})
RA

         RA
0     188.0
1     229.0
2     233.5
3     180.0
4     270.0
...     ...
1675  274.5
1676  221.0
1677  279.0
1678  225.5
1679  172.0

[1680 rows x 1 columns]

In [68]:
rb =(Data3['Pb']*119+Data3['Cd']*95+Data3['Sn']*118+Data3['Mn']*83+Data3['Eu']*117+Data3['Zn']*74)
rb

0       119.0
1       119.0
2       119.0
3       119.0
4       119.0
        ...
1675     74.0
1676     74.0
1677     74.0
1678     74.0
1679     74.0
Length: 1680, dtype: float64

In [69]:
RB = pd.DataFrame(data=rb,columns={'RB'})
RB

         RB
0     119.0
1     119.0
2     119.0
3     119.0
4     119.0
...     ...
1675   74.0
1676   74.0
1677   74.0
1678   74.0
1679   74.0

[1680 rows x 1 columns]

In [70]:
rx = (Data3['Cl']*181+Data3['Br']*196+Data3['I']*220)/3
rx

0       181.0
1       181.0
2       181.0
3       181.0
4       181.0
        ...
1675    220.0
1676    220.0
1677    220.0
1678    220.0
1679    220.0
Length: 1680, dtype: float64

In [71]:
RX = pd.DataFrame(data=rx,columns={'RX'})
RX

         RX
0     181.0
1     181.0
2     181.0
3     181.0
4     181.0
...     ...
1675  220.0
1676  220.0
1677  220.0
1678  220.0
1679  220.0

[1680 rows x 1 columns]

In [43]:
gtf = (ra+rx)/(1.414*(rb+rx))
gtf

0       0.869873
1       0.966525
2       0.977133
3       0.851014
4       1.063178
          ...
1675    1.189514
1676    1.060820
1677    1.200339
1678    1.071645
1679    0.942951
Length: 1680, dtype: float64

In [72]:
GTF = pd.DataFrame(data=gtf,columns={"Goldschmidt's"})
GTF

      Goldschmidt's
0          0.869873
1          0.966525
2          0.977133
3          0.851014
4          1.063178
...             ...
1675       1.189514
1676       1.060820
1677       1.200339
1678       1.071645
1679       0.942951

[1680 rows x 1 columns]

In [73]:
rxb=rx/rb
rab=ra/rb
lrab= np.log(rab)

In [74]:
bartel =(rxb) - 1*(1-(rab/lrab))
bartel

0       3.975564
1       3.460779
2       3.432009
3       4.176115
4       3.290338
          ...
1675    4.802707
1676    4.702607
1677    4.813857
1678    4.707802
1679    4.728775
Length: 1680, dtype: float64

In [75]:
Bartel = pd.DataFrame(data=bartel,columns={'Bartel et al'})
Bartel

      Bartel et al
0         3.975564
1         3.460779
2         3.432009
3         4.176115
4         3.290338
...            ...
1675      4.802707
1676      4.702607
1677      4.813857
1678      4.707802
1679      4.728775

[1680 rows x 1 columns]

In [76]:
sdt = pd.DataFrame(data=(np.ones(1680)),columns={'S/D/T'})

In [83]:
DataF=pd.concat([Data3.iloc[:,:-1],sdt,Data3.iloc[:,-1],RA,RB,RX,GTF,Bartel],axis=1)
DataF

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Cl,Br,I,S/D/T,Dimensionality,RA,RB,RX,Goldschmidt's,Bartel et al
0,Cs1.0Pb1.0Cl3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,188.0,119.0,181.0,0.869873,3.975564
1,Cs0.5MA0.5Pb1.0Cl3.0,0.5,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,229.0,119.0,181.0,0.966525,3.460779
2,Cs0.5FA0.5Pb1.0Cl3.0,0.5,0.0,0.5,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,233.5,119.0,181.0,0.977133,3.432009
3,Cs0.5Rb0.5Pb1.0Cl3.0,0.5,0.0,0.0,0.5,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,180.0,119.0,181.0,0.851014,4.176115
4,MA1.0Pb1.0Cl3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,270.0,119.0,181.0,1.063178,3.290338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,MA0.5FA0.5Zn1.0I3.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,274.5,74.0,220.0,1.189514,4.802707
1676,MA0.5Rb0.5Zn1.0I3.0,0.0,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,221.0,74.0,220.0,1.060820,4.702607
1677,FA1.0Zn1.0I3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,279.0,74.0,220.0,1.200339,4.813857
1678,FA0.5Rb0.5Zn1.0I3.0,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,225.5,74.0,220.0,1.071645,4.707802
1679,Rb1.0Zn1.0I3.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,172.0,74.0,220.0,0.942951,4.728775

In [84]:
DataF.Material=DataF.Material.str.replace("1.0","")
DataF

/var/folders/hy/sb8f_z2j1hxg_09pbh5s7myr0000gn/T/ipykernel_38971/3224014400.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  DataF.Material=DataF.Material.str.replace("1.0","")

,Material,Cs,MA,FA,Rb,Pb,Cd,Bi,Sn,Na,...,Cl,Br,I,S/D/T,Dimensionality,RA,RB,RX,Goldschmidt's,Bartel et al
0,CsPbCl3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,188.0,119.0,181.0,0.869873,3.975564
1,Cs0.5MA0.5PbCl3.0,0.5,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,229.0,119.0,181.0,0.966525,3.460779
2,Cs0.5FA0.5PbCl3.0,0.5,0.0,0.5,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,233.5,119.0,181.0,0.977133,3.432009
3,Cs0.5Rb0.5PbCl3.0,0.5,0.0,0.0,0.5,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,180.0,119.0,181.0,0.851014,4.176115
4,MAPbCl3.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,3.0,0.0,0.0,1.0,0.0,270.0,119.0,181.0,1.063178,3.290338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1675,MA0.5FA0.5ZnI3.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,274.5,74.0,220.0,1.189514,4.802707
1676,MA0.5Rb0.5ZnI3.0,0.0,0.5,0.0,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,221.0,74.0,220.0,1.060820,4.702607
1677,FAZnI3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,279.0,74.0,220.0,1.200339,4.813857
1678,FA0.5Rb0.5ZnI3.0,0.0,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,225.5,74.0,220.0,1.071645,4.707802
1679,RbZnI3.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,1.0,0.0,172.0,74.0,220.0,0.942951,4.728775

In [86]:
DataF.to_excel('single.xlsx')

# Intermediate

In [85]:
DataF.iloc[1589]

Material          RbSnBr0.5I2.5
Cs                          0.0
MA                          0.0
FA                          0.0
Rb                          1.0
Pb                          0.0
Cd                          0.0
Bi                          0.0
Sn                          1.0
Na                          0.0
In                          0.0
Sb                          0.0
K                           0.0
Cu                          0.0
Ag                          0.0
Mn                          0.0
Eu                          0.0
Zn                          0.0
Sc                          0.0
La                          0.0
Y                           0.0
Cl                          0.0
Br                          0.5
I                           2.5
S/D/T                       1.0
Dimensionality              0.0
RA                        172.0
RB                        118.0
RX                        216.0
Goldschmidt's          0.821553
Bartel et al           4.698844
Name: 1589, dtype: object